# Generated by Django 4.0.6 on 2022-07-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('size', models.CharField(max_length=40)),
                ('pair', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=40)),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('В процессе', 'В процессе'), ('Собран', 'Собран'), ('Отгружен', 'Отгружен'), ('Оплачен', 'Оплачен')], max_length=40)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=40)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Working_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('kol_vo', models.IntegerField(default=0)),
                ('workers_defect', models.IntegerField(default=0)),
                ('machines_defect', models.IntegerField(default=0)),
                ('Say_marriage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viplata', models.IntegerField(null=True)),
                ('occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_ocupation', to='manufacture.occupation')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('fio', models.CharField(max_length=64, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('monthly_salary', models.IntegerField(default=0)),
                ('occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_ocupation', to='manufacture.occupation')),
            ],
        ),
    ]
