# Generated by Django 4.0.6 on 2022-07-21 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0003_remove_salarytotal_occupation_salarytotal_oklad_fact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, upload_to='media/products/%Y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('type', models.CharField(max_length=40)),
                ('size', models.CharField(max_length=40)),
                ('rest_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кол-во')),
                ('defect_worker', models.IntegerField(default=0)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacture.catalogue')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=40, verbose_name='Артикул')),
                ('title', models.CharField(max_length=40, verbose_name='Наименование')),
                ('type', models.CharField(max_length=40, verbose_name='Модель')),
                ('size', models.CharField(max_length=40, verbose_name='Размер')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кол-во')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Цена сом')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('В процессе', 'В процессе'), ('Собран', 'Собран'), ('Отгружен', 'Отгружен'), ('Оплачен', 'Оплачен')], max_length=40)),
                ('total', models.DecimalField(decimal_places=2, max_digits=40, verbose_name='Сумма сом')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
        ),
        migrations.DeleteModel(
            name='Prof',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='Working_out',
        ),
        migrations.RemoveField(
            model_name='salarytotal',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='salarytotal',
            name='fact_work_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salarytotal',
            name='firm_social_fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='salarytotal',
            name='month',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salarytotal',
            name='oklad_nachislen',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salarytotal',
            name='social_fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='salarytotal',
            name='working_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salarytotal',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manufacture.employee'),
        ),
        migrations.AddField(
            model_name='salarytotal',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_sales', to='manufacture.sale'),
        ),
        migrations.AddField(
            model_name='salarytotal',
            name='working_out',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture.production'),
        ),
    ]
