# Generated by Django 4.0.6 on 2022-07-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0004_catalogue_production_sale_delete_prof_delete_sales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(max_length=100, verbose_name='Клиент')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
