# Generated by Django 4.0.6 on 2022-07-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0005_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='file',
            field=models.FileField(default='media/clients/index.jpeg', upload_to='media/clients/%Y/%m/%d'),
        ),
    ]
