# Generated by Django 4.0.6 on 2022-08-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0008_user_remove_salarytotal_working_out_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
